# Builds Snort 2.9.x.x Dalton agent using Snort source
# Works for Snort 2.9.16.x and later
# hadolint global ignore=DL3003,SC2046

FROM ubuntu:24.04

ARG SNORT_VERSION
ARG DAQ_VERSION

# tcpdump is for pcap analysis; not *required* for
#  the agent but nice to have....
# changed python3.8 to python3 python3-dev python3-pip
# other additional packages: libtool libtirpc-dev
# hadolint ignore=DL3008
RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    python3 python3-dev python3-pip \
    tcpdump \
    automake libtool autoconf \
    build-essential make flex bison \
    libpcap-dev libpcre3-dev \
    libcap-ng-dev libdumbnet-dev libtirpc-dev \
    zlib1g-dev liblzma-dev openssl libssl-dev \
    libnghttp2-dev libluajit-5.1-dev && \
    ldconfig && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# for debugging agent
# RUN apt-get install -y less nano

# download, build, and install Snort from source
RUN mkdir -p /src/snort-${SNORT_VERSION} && mkdir -p /etc/snort
WORKDIR /src
# DAQ.  Apparently DAQ will sometime fail building with multiple make jobs.
# Discovered that autoreconf is necessary to avoid failures compiling DAQ on 24.04
ADD https://www.snort.org/downloads/archive/snort/daq-${DAQ_VERSION}.tar.gz daq-${DAQ_VERSION}.tar.gz
RUN tar -zxf daq-${DAQ_VERSION}.tar.gz && cd daq-${DAQ_VERSION} && autoreconf -f -i && ./configure && make && make install
# Snort
# Necessary to add CFLAGS="-I/usr/include/tirpc" to point snort to the correctly location for the RPC headers it needs
ADD https://www.snort.org/downloads/archive/snort/snort-${SNORT_VERSION}.tar.gz snort-${SNORT_VERSION}.tar.gz
RUN tar -zxf snort-${SNORT_VERSION}.tar.gz -C snort-${SNORT_VERSION} --strip-components=1 && \
    cd /src/snort-${SNORT_VERSION} && ./configure --enable-sourcefire --enable-debug --enable-buffer-dump CFLAGS="-I/usr/include/tirpc" && make -j $(nproc) && make install && \
    mkdir /usr/local/lib/snort_dynamicrules && ldconfig

RUN cp -t /etc/snort/ /src/snort-${SNORT_VERSION}/etc/classification.config /src/snort-${SNORT_VERSION}/etc/file_magic.conf \
    /src/snort-${SNORT_VERSION}/etc/gen-msg.map /src/snort-${SNORT_VERSION}/etc/reference.config \
    /src/snort-${SNORT_VERSION}/etc/threshold.conf /src/snort-${SNORT_VERSION}/etc/unicode.map; exit 0

RUN mkdir -p /opt/dalton-agent/
WORKDIR /opt/dalton-agent
COPY dalton-agent.py /opt/dalton-agent/dalton-agent.py
COPY dalton-agent.conf /opt/dalton-agent/dalton-agent.conf

CMD ["python3", "/opt/dalton-agent/dalton-agent.py", "-c", "/opt/dalton-agent/dalton-agent.conf"]
