# spin up nginx with custom conf
FROM nginx:1.13.5
MAINTAINER David Wharton

RUN rm /etc/nginx/nginx.conf && rm -rf /etc/nginx/conf.d
COPY nginx-conf/nginx.conf /etc/nginx/nginx.conf
COPY nginx-conf/conf.d /etc/nginx/conf.d

CMD nginx
