# Builds Suricata 4.0.0 Dalton agent using Suricata source tarball
FROM ubuntu:16.04
MAINTAINER David Wharton

# tcpdump is for pcap analysis; not *required* for
#  the agent but nice to have....
RUN apt-get update -y && apt-get install -y \
    python=2.7.11-1 \
    tcpdump=4.9.0-1ubuntu1~ubuntu16.04.1 \
    libpcre3 libpcre3-dbg libpcre3-dev \
    build-essential autoconf automake libtool libpcap-dev libnet1-dev \
    libyaml-0-2 libyaml-dev zlib1g zlib1g-dev libcap-ng-dev libcap-ng0 \
    make libmagic-dev libjansson-dev libjansson4 pkg-config wget

# for debugging agent
RUN apt-get install -y less nano

RUN mkdir /src
WORKDIR /src
RUN wget https://www.openinfosecfoundation.org/download/suricata-4.0.0.tar.gz
RUN tar -xzf suricata-4.0.0.tar.gz
WORKDIR /src/suricata-4.0.0
RUN /bin/bash configure --enable-profiling
RUN make && make install && make install-conf && ldconfig

RUN mkdir -p /opt/dalton-agent/
WORKDIR /opt/dalton-agent
COPY dalton-agent.py /opt/dalton-agent/dalton-agent.py
COPY dalton-agent.conf /opt/dalton-agent/dalton-agent.conf

CMD python /opt/dalton-agent/dalton-agent.py -c /opt/dalton-agent/dalton-agent.conf 2>&1

