# Builds Suricata 3.0 Dalton agent using Suricata from Ubuntu repos
FROM ubuntu:16.04
MAINTAINER David Wharton

# tcpdump is for pcap analysis; not *required* for
#  the agent but nice to have....
RUN apt-get update -y && apt-get install -y \
    python=2.7.11-1 \
    tcpdump=4.9.0-1ubuntu1~ubuntu16.04.1

RUN apt-get install -y suricata=3.0-1

#RUN apt-get install -y python-pip
#RUN pip install -U pip
#RUN pip install https://github.com/jasonish/py-idstools/archive/master.zip

RUN mkdir -p /opt/dalton-agent/

WORKDIR /opt/dalton-agent

COPY dalton-agent.py /opt/dalton-agent/dalton-agent.py
COPY dalton-agent.conf /opt/dalton-agent/dalton-agent.conf

CMD python /opt/dalton-agent/dalton-agent.py -c /opt/dalton-agent/dalton-agent.conf 2>&1 | tee /var/log/dalton-agent.log

