# Builds Suricata 3.0 Dalton agent using Suricata from Ubuntu repos
FROM ubuntu:16.04
MAINTAINER David Wharton

# tcpdump for pcap analysis; not *requried* for
#  the agent but nice to have....
#  should be included in wireshark anyway (see below)
RUN apt-get update -y && apt-get install -y \
    python-dev \
    tcpdump

RUN apt-get install -y suricata=3.0-1

RUN apt-get install -y python-pip
RUN pip install -U pip
RUN pip install https://github.com/jasonish/py-idstools/archive/master.zip

# wireshark needed for mergecap; statically compiled
#  mergecap would be smaller but doing this for now
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install wireshark

RUN mkdir -p /opt/dalton-agent/

WORKDIR /opt/dalton-agent

COPY dalton-agent.py /opt/dalton-agent/dalton-agent.py
COPY dalton-agent.conf /opt/dalton-agent/dalton-agent.conf

CMD python /opt/dalton-agent/dalton-agent.py -c /opt/dalton-agent/dalton-agent.conf 2>&1 | tee /var/log/dalton-agent.log

